services:
  web:
    build: .
    restart: always
    environment:
      FLASK_HOST: "${FLASK_HOST}"
      FLASK_ENV: "${FLASK_ENV}"
      FLASK_PASSWORD: "${FLASK_PASSWORD}"
      DEFAULT_PASSWORD: "${DEFAULT_PASSWORD}"
      DATABASE_URI: "${DATABASE_URI}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    ports:
      - '8081:5000'
    volumes:
      - .:/job_swipe
    networks:
      - job-swipe-network

networks:
  job-swipe-network:
    name: job-swipe-network
    driver: bridge
    external: true
